# This workflow will publish qaf artifacts
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Deploy CI

on: 
  workflow_dispatch:
    inputs:
      status:
        description: 'publish status: releases or snapshots'     
        required: true
        default: 'releases'
      resolver:
        description: 'publish resolver: staging or snapshots'     
        required: true
        default: 'staging'
      version:
        description: 'version-num' 
        required: true
        default: '3.2'
      build:
        description: 'build-num' 
        required: true
        default: '0-SNAPSHOT'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-gpg@v3
    - name: Install gpg secret key
      run: |
        cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
        gpg --list-secret-keys --keyid-format LONG
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Ant
      run: |
        export GPG_TTY
        ant -noinput -buildfile build.xml build ivy-publish-share -Dskip.download=false  -Dpublish.resolver=nexus-${{ github.event.inputs.resolver }} -Dstatus=${{ github.event.inputs.status }} -D"release.num=${{ github.event.inputs.version }}.${{ github.event.inputs.build }}" -D"ivy.revision=${{ github.event.inputs.version }}.${{ github.event.inputs.build }}" -Dgpg.pwd=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} -Dgpg.name=34FAB61338CB5AC4 -Dsonatype.user=${{ secrets.SONATYPE_USER }} -Dsonatype.pwd=${{ secrets.SONATYPE_SEC }}
