# This workflow will publish qaf artifacts
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: tag release

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'version-num' 
        required: true
        default: '3.2'
      build:
        description: 'build-num' 
        required: true
        default: '0-SNAPSHOT'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Ant
      run: |
        ant -noinput -buildfile build.xml tag-release-all -Dskip.download=false -D"release.num=${{ github.event.inputs.version }}.${{ github.event.inputs.build }}" -D"ivy.revision=${{ github.event.inputs.version }}.${{ github.event.inputs.build }}"
